-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 21:58:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gym` ;

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym` DEFAULT CHARACTER SET utf8 ;
USE `gym` ;

-- -----------------------------------------------------
-- Table `gym`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`gender` ;

CREATE TABLE IF NOT EXISTS `gym`.`gender` (
  `id_gender` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`user` ;

CREATE TABLE IF NOT EXISTS `gym`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `last_log` DATETIME NOT NULL,
  `id_gender` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_gender1_idx` (`id_gender` ASC),
  CONSTRAINT `fk_user_gender1`
    FOREIGN KEY (`id_gender`)
    REFERENCES `gym`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`tokenization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`tokenization` ;

CREATE TABLE IF NOT EXISTS `gym`.`tokenization` (
  `id_token` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_token`),
  INDEX `fk_tokenization_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_tokenization_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `gym`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`predisposition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`predisposition` ;

CREATE TABLE IF NOT EXISTS `gym`.`predisposition` (
  `id_predisposition` INT NOT NULL AUTO_INCREMENT,
  `height` INT NOT NULL,
  `weight` INT NOT NULL,
  `waist size` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_predisposition`),
  INDEX `fk_predisposition_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_predisposition_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `gym`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`appointment` ;

CREATE TABLE IF NOT EXISTS `gym`.`appointment` (
  `id_appointment` INT NOT NULL AUTO_INCREMENT,
  `appointments_time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_appointment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`days` ;

CREATE TABLE IF NOT EXISTS `gym`.`days` (
  `id_days` INT NOT NULL AUTO_INCREMENT,
  `days` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_days`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`schedule` ;

CREATE TABLE IF NOT EXISTS `gym`.`schedule` (
  `id_schedule` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_days` INT NOT NULL,
  `id_appointment` INT NOT NULL,
  `schedule_date` DATE NOT NULL,
  PRIMARY KEY (`id_schedule`),
  INDEX `fk_scheduling_days1_idx` (`id_days` ASC),
  INDEX `fk_scheduling_user1_idx` (`id_user` ASC),
  INDEX `fk_schedule_appointment1_idx` (`id_appointment` ASC),
  CONSTRAINT `fk_scheduling_days1`
    FOREIGN KEY (`id_days`)
    REFERENCES `gym`.`days` (`id_days`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scheduling_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `gym`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_appointment1`
    FOREIGN KEY (`id_appointment`)
    REFERENCES `gym`.`appointment` (`id_appointment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`programs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`programs` ;

CREATE TABLE IF NOT EXISTS `gym`.`programs` (
  `id_programs` INT NOT NULL AUTO_INCREMENT,
  `slim_female` VARCHAR(45) NOT NULL,
  `fat_female` VARCHAR(45) NOT NULL,
  `slim_male` VARCHAR(45) NOT NULL,
  `fat_male` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_programs`),
  INDEX `fk_programs_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_programs_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `gym`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`message` ;

CREATE TABLE IF NOT EXISTS `gym`.`message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `messanger_name` VARCHAR(45) NOT NULL,
  `messanger_email` VARCHAR(45) NOT NULL,
  `message` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id_message`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`subscribe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym`.`subscribe` ;

CREATE TABLE IF NOT EXISTS `gym`.`subscribe` (
  `id_subscribe` INT NOT NULL AUTO_INCREMENT,
  `subscriber_name` VARCHAR(45) NOT NULL,
  `subscriber_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_subscribe`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
